Update fake-make

diff --git a/fake-make b/fake-make
--- a/fake-make
+++ b/fake-make
@@ -29,7 +29,10 @@ function make {
     fi
     ltmp="/tmp/fmake_$(echo "${lcwd}_:_${ldir}_:_${ltargets}" | md5sum | cut -d ' ' -f 1).$$"
     grep -v "^[A-Z]+=" "$lmakefile" > "$ltmp"
-    grep "^[A-Z]+=" "$lmakefile" | tac | sed 's/^\([A-Z][A-Z]*\)=\(.*\)/s\/$(\1)\/\2/' | xargs -t -I '{}' sed -i '{}' "$ltmp"
+    lout="$(grep "^[A-Z]+=" "$lmakefile" | tac | sed 's/^\([A-Z][A-Z]*\)=\(.*\)/s\/$(\1)\/\2/')"
+    if [[ "$ltmp" != "" ]]; then
+	printf "%" "$lout" | xargs -t -I '{}' sed -i '{}' "$ltmp"
+    fi
     sed -i 's/$(MAKE)/make/' "$ltmp"
     lout="$ltmp.prgrs"
 
@@ -103,10 +106,18 @@ function make_target {
     fi
     #echo "$lvar"
     echo '#!/bin/bash' > "$3.target"
-    tail -n "+$lm" "$1" | head -n "$lvar" | grep -o '^'$'\t''[^#]+' | grep -o '[^'$'\t''].*' | xargs -I '{}' printf '( %s );\nretval=$?\nif [[ "$retval" != "0" ]]; then\n  return "$retval"\nfi\n' '{}' >> "$3.target"
-    lvar="$(pwd)"
-    make_run "$3.target"
-    cd "$lvar"
+    lvar="$(tail -n "+$lm" "$1" | head -n "$lvar" | grep -o '^'$'\t''[^#]+' | grep -o '[^'$'\t''].*')"
+    if [[ "$lvar" != "" ]]; then
+	printf "%s" "$lvar" | xargs -I '{}' printf '( %s );\nretval=$?\nif [[ "$retval" != "0" ]]; then\n  return "$retval"\nfi\n' '{}' >> "$3.target"
+	lvar="$(pwd)"
+	make_run "$3.target"
+	retval=$?
+	cd "$lvar"
+	if [[ "$retval" != 0 ]]; then
+	    echo "!!! Target '$2' failed."
+	    return "$retval"
+	fi
+    fi
 }
 
 function make_run {
